import type { Metadata, Viewport } from 'next';
import { Geist } from 'next/font/google';
import Navbar from '@/components/navbar';

import './globals.css';

// @theme, https://tailwindcss.com/docs/theme
const geistSans = Geist({
    subsets: ['latin'],
    display: 'swap',
});

// favicon generator https://realfavicongenerator.net/
export const metadata: Metadata = {
    title: 'Langfuse-graph',
    description: 'Generated by woongsik',
    icons: {
        icon: '/favicon.png',
    },
};

export const viewport: Viewport = {
    // themeColor: [
    //     { media: '(prefers-color-scheme: light)', color: 'black' },
    //     { media: '(prefers-color-scheme: dark)', color: 'white' },
    // ],
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
    themeColor: 'black',
    colorScheme: 'dark',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // https://tailwindcss.com/docs/font-smoothing
    return (
        <html
            lang="en"
            // https://nextjs.org/docs/app/api-reference/components/font#css-variables
            // https://tailwindcss.com/docs/background-image
        >
            <body
                className={`${geistSans.className} antialiased body-scrollbar mx-auto cursor-default`}
            >
                <div className="mx-8 my-4">
                    <div className="text-center">
                        <p className="text-3xl font-bold">Langfuse-graph</p>
                        <p className="mt-4 text-base text-gray-300">
                            😃 Agent Evaluation 😃
                        </p>
                    </div>
                    <div className="my-4">
                        <div className="rounded-l-3xl border border-2 border-blue-300 shadow-2xl shadow-blue-300">
                            <Navbar />
                            {/* - 기본: 35rem (560px) - 작은 화면
                            - lg (1024px): 40rem (640px) - 일반 모니터
                            - xl (1280px): 45rem (720px) - 큰 모니터
                            - 2xl (1536px): 50rem (800px) - 초고해상도 */}
                            <main
                                className="graphs-scrollbar overflow-y-scroll
                             h-[35rem]
                             lg:h-[40rem]
                             xl:h-[45rem] 
                             2xl:h-[50rem]"
                            >
                                {children}
                            </main>
                        </div>
                    </div>
                </div>
            </body>
        </html>
    );
}
